### ISSUE TITLE
ifdef _cplusplus

### ISSUE THREAD

**Issue by tmnvanderberg** [PE5E/ICCE#2]
It is useless to `add ifdef __cplusplus` if you use _any_ c++ specific code. (you still won't be able to compile it in C compiler ). I think we should therefore avoid using it, and write pure (specialised as frank calls it) c++ headers.

What do you think?

**Comment by PE5E** [comment]
I 'm all for clarity. So fine by me.
This header style was thought to us and I am not totally sure why at this moment.
